apiVersion: v1
kind: Service
metadata:
  name: mswebsocket
  namespace: sit
  labels:
    app: mswebsocket
spec:
  selector:
    app: mswebsocket
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8990